name: bitmap_example
description: Demonstrates how to use the bitmap plugin.
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^5.1.0
  bitmap:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/doggo.jpeg
    - assets/street.jpg
